name: Build macOS

on:
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-latest

    defaults:
      run:
        working-directory: ./GraveFallGame

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build macOS app
        run: npm run dist:mac

      - name: Upload macOS build
        uses: actions/upload-artifact@v4
        with:
          name: GraveFallGame-macOS
          path: GraveFallGame/release/*.dmg
